name: Linter check and cppcheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build essentials and clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang-format cppcheck

    - name: Run lint
      run: clang-format -i --style=Google **/*.cpp **/*.h
    - name: Run cppcheck
      run: cppcheck --language=c++ **/*.cpp **/*.h